### ISSUE TITLE
Location page

### ISSUE THREAD

**Issue by LaserRayGunBOSS** [thefootlightbar/thefootlightbar.github.io#10]
Heyyy! Could we please have a Locations tab on the website, with the stuff below? <3

Footlight is a perfect place to film, thanks to our acoustic treatment and easy to black out windows and doors. 1000 sq feet venue, 500 sq ft bar area. Vintage ballroom floor and stage. Backline available for use or as props. Sound tech upon request. Negotiable day rates and flexible hours. Email footlightbar@gmail.com for location rental inquires.

![location2](https://user-images.githubusercontent.com/39224113/64644903-b5a36f00-d3e1-11e9-9280-b09c0327fbba.jpeg)
![location3](https://user-images.githubusercontent.com/39224113/64644905-b5a36f00-d3e1-11e9-8c10-fbf9e25a74c2.jpg)
![location](https://user-images.githubusercontent.com/39224113/64644908-b89e5f80-d3e1-11e9-83f7-e7a92c1b2df0.jpeg)
![location4](https://user-images.githubusercontent.com/39224113/64645199-55f99380-d3e2-11e9-8c0a-76759ae07ead.jpg)

![location6](https://user-images.githubusercontent.com/39224113/64645201-55f99380-d3e2-11e9-91f4-03951dda0d94.jpg)

**Comment by LaserRayGunBOSS** [comment]
This one, instead of that second to last one! Sorry!

![location7](https://user-images.githubusercontent.com/39224113/64645337-b5f03a00-d3e2-11e9-9304-64496b844076.jpg)

**Comment by meitar** [comment]
Closed in dc65d960ad7e83f28cb297e2bccc7c185845d89d.
