### ISSUE TITLE
images not loading

### ISSUE THREAD

**Issue by LaserRayGunBOSS** [thefootlightbar/thefootlightbar.github.io#7]
Hi! I feel like the images aren't loading consistently. I am typing IMAGE: ghsjkash.jpg for every image. Some load, some come in and out.

**Comment by meitar** [comment]
I see a few broken images as well, but they're all consistent. I fixed one in commit 04cafe17fde7a68e76c8b2f27be4d74213b5c6d9 simply by renaming the file. The image in the event data was listed as `forthefuture.jpg` but it was originally uploaded by @elryrie as `forthefuture (1).jpg` in commit b27faaba7404792f50dede21fa736edd4e387cd5. Probably an innocent oversight.

There are two additional event images that are broken as far as I can see:

1. Hail Mary: Our Queer Saints, on September 13, 2019. The event data expects an image file whose name is `HM Standing Image.jpg` but no such file exists in [the site's `static/images` folder](https://github.com/thefootlightbar/thefootlightbar.github.io/tree/master/static/images). So, that image still needs to be uploaded.
1. Oh Ecstasy, True Dreams, Screamcloud, Monster Furniture, on September 18, 2019. The event data for this show is expecting an image named `66069196_480567839369684_7646619792224288768_o.jpg` to exist. This seems like it's an image downloaded from Facebook maybe? But again, no such image file with this name exists in the site's `static/images` folder, so it needs to be added.

Other than that, all the images on the site are loading okay for me. I'm going to close this issue with the suggestion that the missing images be uploaded, but feel free to re-open this and provide some additional information if you were referring to something beyond my observations regarding the above.
